APP_PORT  := `yq '.application.port' config.yaml`
APP_HOST  := `yq '.application.host' config.yaml`

DB_HOST   := `yq '.database.host' config.yaml`
DB_PORT   := `yq '.database.port' config.yaml`
DB_NAME   := `yq '.database.db_name' config.yaml`
DB_USER   := `yq '.database.username' config.yaml`
DB_PSWD   := `yq '.database.password' config.yaml`

curl:
  @curl -sS http://{{APP_HOST}}:{{APP_PORT}} | jq

pg_url: 
  @echo "postgres://{{DB_USER}}:{{DB_PSWD}}@localhost:{{DB_PORT}}/{{DB_NAME}}"

psql:
  @psql -h localhost -U {{DB_USER}} -p {{DB_PORT}} -d {{DB_NAME}} -W

migrate:
  sqlx database create --database-url="$(just pg_url)"
  sqlx migrate run --database-url="$(just pg_url)"

up:
  docker compose -f compose.yaml down
  docker compose -f compose.yaml up -d
