[target.'cfg(target_os = "none")']
runner = "bootimage runner"		# Run the kernel with QEMU
# qemu-system-x86_64 -drive format=raw,
#	file=target/x86_64-blog_os/debug/bootimage-ross.bin
# dd if=target/x86_64-blog_os/debug/bootimage-ross.bin
#	of=/dev/sdX && sync

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]	# Links the program

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
# Tells cargo that it should recompile the core and compiler_builtins
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-ross.json"
