[package]
name = "rust_numerical"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
dialoguer = "0.9.0"
indicatif = "0.16.2"
