[package]
name = "rs_randomguess"
version = "0.1.0"
edition = "2018"
authors = ["Danyiel Colin danyiel5978@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.0"
